### ISSUE TITLE
Nieuwe partner formulier design

### ISSUE THREAD

**Issue by DaanCarst** [WesleySchorel/Toolgankelijk-Sprint-18#7]
# **Component specific**
- [x] Nieuwe pagina met formulier
- [x] Kunnen posten van het formulier

## **Controle**

**Is het component responsive en voldoet het aan de huisstijl?**
- [ ] Alles werkt op Desktop
- [ ] Alles werkt op Tablet
- [ ] Alles werkt op Mobile

**Voldoet het component aan de afgesproken coding standards?** 
- [ ] Web standaarden
- [ ] Semantische 
- [ ] Atomic design
- [ ] Imports bovenaan
- [ ] Styling onderaan

**Is het component toegankelijk?** 
- [ ] Lighthouse toegankelijk test
- [ ] Handmatige test

**Is het component performant?**
- [ ] Lighthouse performance test

**Comment by Tolga1999** [comment]
- [ ] nieuwe pagina met formulier
- [ ] kunnen posten van het formulier
